### ISSUE TITLE
Tracking issue for references

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/path_semantics#597]
- [x] The History of Path Semantics
- [x] How to Think Abstractly With Path Semantics (TODO: "With" => "with")
- [ ] Path Semantics Cheat Sheet (ignore)
- [ ] Goals of path semantics (TODO: Fix capitals in title)
- [ ] Atomic functions
- [x] Path semantics (TODO: Fix capitals in title)
- [x] Lifted Associations
- [x] Asserting Formal Associations
- [x] Computational Equivalence
- [x] Incompleteness of Path Semantics
