### ISSUE TITLE
Tracking issue for research-todo

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/path_semantics#600]
- [ ] 2-bit mini language for reference grammar 
  - `{}` for repeat block, `x` for product type, `,` for sum type
  - Uses between-the-lines self reference addressing
- [ ] Infibin: Figure out fast algorithm for ancestor/descendant detection
- [ ] Infibin: Figure out fast algorithm for optimal navigation between two numbers
- [ ] Infibin: Produce non-trivial example of self-symmetric path
