### ISSUE TITLE
Convert from meta data to interpreter instructions

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/path_semantics#70]
Could do a straight forward conversion, mapping terms to a hash map. This will allow writing unit tests in the notation.
- [x] Simple straight forward conversion
- [ ] Return hash map of the term names
- [ ] Allow any order of functions

**Comment by bvssvni** [comment]
Closing since decided to not work on programming language implementation.
